// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  integrations: [
    starlight({
      title: 'Math On Canvas',
      logo: {
        src: './src/assets/logo.svg',
        alt: 'Math On Canvas',
      },
      customCss: ['./src/styles/theme.css'],
      components: {
        ThemeSelect: './src/components/starlight/ThemeSelect.astro',
      },
      locales: {
        root: { label: 'English', lang: 'en' },
        ru:   { label: 'Русский', lang: 'ru' },
        de:   { label: 'Deutsch', lang: 'de' },
        es:   { label: 'Español', lang: 'es' },
      },
      defaultLocale: 'root',
      sidebar: [
        {
          label: 'Getting Started',
          translations: { ru: 'Начало работы', de: 'Erste Schritte', es: 'Empezando' },
          items: [
            { label: 'Introduction', slug: 'getting-started/introduction',
              translations: { ru: 'Введение', de: 'Einführung', es: 'Introducción' } },
            { label: 'Quick Start', slug: 'getting-started/quick-start',
              translations: { ru: 'Быстрый старт', de: 'Schnellstart', es: 'Inicio rápido' } },
            { label: 'Interface Overview', slug: 'getting-started/interface',
              translations: { ru: 'Обзор интерфейса', de: 'Oberfläche', es: 'Interfaz' } },
          ],
        },
        {
          label: 'Guides',
          translations: { ru: 'Руководства', de: 'Anleitungen', es: 'Guías' },
          items: [
            { label: 'Formulas', slug: 'guides/formulas',
              translations: { ru: 'Формулы', de: 'Formeln', es: 'Fórmulas' } },
            { label: 'Mathematical Symbols', slug: 'guides/symbols',
              translations: { ru: 'Математические символы', de: 'Mathematische Symbole', es: 'Símbolos matemáticos' } },
            {
              label: '2D Shapes',
              translations: { ru: '2D-фигуры', de: '2D-Formen', es: 'Figuras 2D' },
              items: [
                { label: 'Overview', slug: 'guides/shapes-2d',
                  translations: { ru: 'Обзор', de: 'Übersicht', es: 'Resumen' } },
                { label: 'Circle', slug: 'guides/shapes-2d/circle',
                  translations: { ru: 'Окружность', de: 'Kreis', es: 'Círculo' } },
                { label: 'Rectangle', slug: 'guides/shapes-2d/rectangle',
                  translations: { ru: 'Прямоугольник', de: 'Rechteck', es: 'Rectángulo' } },
                { label: 'Triangle', slug: 'guides/shapes-2d/triangle',
                  translations: { ru: 'Треугольник', de: 'Dreieck', es: 'Triángulo' } },
                { label: 'Polygon & Polyline', slug: 'guides/shapes-2d/polygon',
                  translations: { ru: 'Многоугольник и ломаная', de: 'Polygon', es: 'Polígono' } },
                { label: 'Line & Arrow', slug: 'guides/shapes-2d/line-arrow',
                  translations: { ru: 'Линия и стрелка', de: 'Linie & Pfeil', es: 'Línea y flecha' } },
              ],
            },
            {
              label: '3D Shapes',
              translations: { ru: '3D-фигуры', de: '3D-Formen', es: 'Figuras 3D' },
              items: [
                { label: 'Overview', slug: 'guides/shapes-3d',
                  translations: { ru: 'Обзор', de: 'Übersicht', es: 'Resumen' } },
                { label: 'Cube', slug: 'guides/shapes-3d/cube',
                  translations: { ru: 'Куб', de: 'Würfel', es: 'Cubo' } },
                { label: 'Sphere', slug: 'guides/shapes-3d/sphere',
                  translations: { ru: 'Сфера', de: 'Kugel', es: 'Esfera' } },
                { label: 'Cone', slug: 'guides/shapes-3d/cone',
                  translations: { ru: 'Конус', de: 'Kegel', es: 'Cono' } },
                { label: 'Cylinder', slug: 'guides/shapes-3d/cylinder',
                  translations: { ru: 'Цилиндр', de: 'Zylinder', es: 'Cilindro' } },
                { label: 'Prism', slug: 'guides/shapes-3d/prism',
                  translations: { ru: 'Призма', de: 'Prisma', es: 'Prisma' } },
                { label: 'Pyramid', slug: 'guides/shapes-3d/pyramid',
                  translations: { ru: 'Пирамида', de: 'Pyramide', es: 'Pirámide' } },
              ],
            },
            { label: 'Text', slug: 'guides/text',
              translations: { ru: 'Текст', de: 'Text', es: 'Texto' } },
            { label: 'Drawing', slug: 'guides/drawing',
              translations: { ru: 'Рисование', de: 'Zeichnen', es: 'Dibujo' } },
            { label: 'Images', slug: 'guides/images',
              translations: { ru: 'Изображения', de: 'Bilder', es: 'Imágenes' } },
            { label: 'Annotations', slug: 'guides/annotations',
              translations: { ru: 'Аннотации', de: 'Anmerkungen', es: 'Anotaciones' } },
            { label: 'Connections & Vertices', slug: 'guides/connections',
              translations: { ru: 'Связи и вершины', de: 'Verbindungen', es: 'Conexiones' } },
            { label: 'Pages & Documents', slug: 'guides/pages-documents',
              translations: { ru: 'Страницы и документы', de: 'Seiten & Dokumente', es: 'Páginas y documentos' } },
            { label: 'AI Assistant', slug: 'guides/ai-assistant',
              translations: { ru: 'ИИ-ассистент', de: 'KI-Assistent', es: 'Asistente IA' } },
            { label: 'Export', slug: 'guides/export',
              translations: { ru: 'Экспорт', de: 'Exportieren', es: 'Exportar' } },
          ],
        },
        {
          label: 'Reference',
          translations: { ru: 'Справочник', de: 'Referenz', es: 'Referencia' },
          items: [
            { label: 'Keyboard Shortcuts', slug: 'reference/keyboard-shortcuts',
              translations: { ru: 'Горячие клавиши', de: 'Tastaturkürzel', es: 'Atajos de teclado' } },
            { label: 'Element Properties', slug: 'reference/element-properties',
              translations: { ru: 'Свойства элементов', de: 'Elementeigenschaften', es: 'Propiedades de elementos' } },
            { label: 'Supported Formats', slug: 'reference/export-formats',
              translations: { ru: 'Форматы экспорта', de: 'Exportformate', es: 'Formatos de exportación' } },
          ],
        },
      ],
    }),
  ],
});